## NumPy 활용하기
### 1. NumPy 의 장점
    1) 선형 대수(행렬 연산 등) 지원
    2) 수학 계산 속도 최적화
    3) Broadcast 기능
    4) 난수 기능
    5) C/C++, Fortran 통합도구

In [1]:
import numpy as np  #넘파이를 사용하기 위한 모듈 임포트, as를 사용하여 사용할 때 이름을 간소화 할 수 있다.
np.__version__ # 'np.' 으로 넘파이모듈 안의 클래스와 함수에 접근한다. 넘파이 버전 확인하는 함수.

'1.16.4'

#### 수학 계산 속도의 최적화 예시

In [2]:
import numpy as np
n = 10000000
w = []                # 파이썬의 기본 list type
x = []
for i in range(n):     #range(n): n 미만의 양의 정수 배열을 생성한다.
    w.append(i*0.00001)
    x.append(i*0.00002)

w_numpy = np.array(w)  # 넘파이의 행렬과 관련된 ndarray type
x_numpy = np.array(x)

In [3]:
%%timeit   
total = 0
for i in range(n):
    total += w[i]*x[i]
"""    
주피터 노트북에서는 셀의 실행 순서에 따라 구문을 처리한다. 앞쪽 셀을 먼저 실행시키면 앞쪽의 내용이 사용된다.
'%%'는 주피터 노트북의 매직 커맨드를 실행한다. 
%%은 반드시 맨 앞에 쓰여야 한다. 주석도 안된다.
%%timeit은 셀을 반복실행하여 실행속도를 평균내어 준다.
"""

1.96 s ± 327 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [4]:
%%timeit
total_numpy = np.dot(w_numpy, x_numpy) 
"""
np.dot은 벡터의 내적을 의미한다. 각각의 n째항을 곱하여 더하는 연산이다.
np.dot대신 @를 사용하거나 w_numpy@x_numpy
w_numpy.dot(x_numpy) 처럼 사용가능하다.
"""

17.5 ms ± 2.19 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


#### ndarray : NumPy의 배열
    numpy에서 배열은 파이썬에서 사용되는 기본 배열과 조금 다르다.
    행렬과 같은 형태로 제공되고 행렬이 가진 속성 데이터도 출력 할 수 있다.
- shape : 행렬의 모양, 항의 개수가 행렬의 차원이 된다. ex) (2,2) 2차 정사각행렬
- size : 행렬 안에 들어가는 모든 데이터의 개수. 즉 shape의 각 항의 곱이랑 같다.
- dtype : 행렬 안에 들어가는 데이터의 타입(b, i8, u8,f8, c16(복소수 부동소수점), O, S24, U24 등등)
- ndim : 행렬의 차원, 정의된 축(axis)의 개수

In [5]:
def aprint(a):  #파이썬의 함수의 정의 def 함수명(변수):
    print("type:{}, dtype:{}".format(type(a), a.dtype))
    print("shape:{}, ndim:{}, size:{}".format(a.shape, a.ndim, a.size))
    print(a)

In [6]:
a = np.arange(12)  
"""
파이썬에서 1차원 배열 생성하기 arange는 range와 다르게 ndarray로 바로 생성해 줌.
arange(시작, 끝(미만), 단계, dtype=데이터 타입)
linspace(시작, 끝(미만), num=데이터 개수, endpoint=True, retstop=False)
시작과 끝까지 데이터 개수만큼 등차수열로 생성하고 반환함
logspace(시작, 끝(미만), num=데이터 개수, endpoint=True, base=10.0)
밑이 10인 로그의 값으로 균등 데이터 개수만큼 나누어 생성하고 반환함
"""
b = [[1,2,3,4],[5,6,7,8]]
b = np.array(b) 
c = np.array((1,3,5,7))
#파이썬의 list와 tuple을 array로 바꿀 수 있음.
aprint(a)
aprint(b)
aprint(c)

type:<class 'numpy.ndarray'>, dtype:int32
shape:(12,), ndim:1, size:12
[ 0  1  2  3  4  5  6  7  8  9 10 11]
type:<class 'numpy.ndarray'>, dtype:int32
shape:(2, 4), ndim:2, size:8
[[1 2 3 4]
 [5 6 7 8]]
type:<class 'numpy.ndarray'>, dtype:int32
shape:(4,), ndim:1, size:4
[1 3 5 7]


In [7]:
#생성된 배열이나 배열을 생성할 때 배열의 모양과 데이터 타입을 바꿀 수 있음.
a = np.arange(12,dtype = float).reshape((3,4))
aprint(a)

type:<class 'numpy.ndarray'>, dtype:float64
shape:(3, 4), ndim:2, size:12
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [8]:
x = np.zeros((3,3)) #0으로 채워진 행렬을 만든다.
aprint(x)
x = np.zeros_like(a)  #주어진 행렬의 모양과 똑같은 크기의 0으로 채워진 행렬을 만든다.
aprint(x)
x = np.ones((3,2)) #1로 채워진 행렬을 만든다.
aprint(x)
x = np.ones_like(a)  #주어진 행렬의 모양과 똑같은 크기의 1로 채워진 행렬을 만든다.
aprint(x)
x = np.full((3,4),2) #주어진 원소로 채워진 행렬을 만든다.
aprint(x)
x = np.empty((2,3), dtype = "f8") #임의의 원소로 채워진 행렬을 만든다.
x

type:<class 'numpy.ndarray'>, dtype:float64
shape:(3, 3), ndim:2, size:9
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
type:<class 'numpy.ndarray'>, dtype:float64
shape:(3, 4), ndim:2, size:12
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
type:<class 'numpy.ndarray'>, dtype:float64
shape:(3, 2), ndim:2, size:6
[[1. 1.]
 [1. 1.]
 [1. 1.]]
type:<class 'numpy.ndarray'>, dtype:float64
shape:(3, 4), ndim:2, size:12
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
type:<class 'numpy.ndarray'>, dtype:int32
shape:(3, 4), ndim:2, size:12
[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


array([[1., 1., 1.],
       [1., 1., 1.]])

#### 배열의 인덱싱, 슬라이싱

In [51]:
a = np.arange(18).reshape((3,6))
print(a,"\n")

#인덱싱
print("a[2,4]=",a[2,4]) #(2,4)위치 출력하기 셋째 행의 다섯 번째 열 값을 출력한다. a[2][4]과 같다.
#가로줄이 행(row)이고 세로줄이 열(column)이다.
print("a[-2,-1]=",a[-2,-1]) # 마이너스 인덱스가 가능하다 뒤에서부터 센다.
print("\n a[1]\n", a[1]) #2행 출력하기


#슬라이싱
print("\n a[:,3]\n", a[:,3]) #3열 출력하기 시작:끝(미만)이고 :은 전체이다.
print("\n a[:2,2:5]\n", a[:2,2:5]) #1~2행, 2~4열 출력하기
print("\n a[-1, 1:6:2]\n", a[1, 1:6:2]) #마지막행에서 2~5열을 2개 간격으로 출력한다.

#index Array boolean 인덱스 배열로 배열의 값 불러오기
b = [True,True,False]
print("\n", a[b,:2])
print("\n",a[a%2 ==0])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]] 

a[2,4]= 16
a[-2,-1]= 11

 a[1]
 [ 6  7  8  9 10 11]

 a[:,3]
 [ 3  9 15]

 a[:2,2:5]
 [[ 2  3  4]
 [ 8  9 10]]

 a[-1, 1:6:2]
 [ 7  9 11]

 [[0 1]
 [6 7]]

 [ 0  2  4  6  8 10 12 14 16]
